create database ursqldb;
use ursqldb;
create table userinfo (id integer primary key auto_increment, name varchar not null, age int not null, address varchar);
show tables;
desc table userinfo;
insert into userinfo (name, age, address) values ('user1', 24, "mirage"), ("another_user", 18, 'inferno');
select * from userinfo order by id;
select name, address, age from userinfo where age = 18 and address == 'inferno';
delete from userinfo where id = 1;
select * from userinfo;
insert into userinfo (name, age) values ('Lanaya', 55), ("Mirana", 66), ("Kunkka", 22), ("Kalashnikov", 100);
select * from userinfo;
select name from userinfo where 30 < age order by name;
update userinfo set age = 80 where age > 80;
select * from userinfo;
drop table userinfo;
drop database ursqldb;